server:
  port: ${CONFIG_PORT:8888}

spring:
  security:
    user:
      name: ${CONFIG_USERNAME:configUser}
      password: ${CONFIG_PASSWORD:configPassword}
      roles: SYSTEM
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LittleJ0hnny/CloudTemplateConfig.git

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${DISCOVERY_USERNAME:discUser}:${DISCOVERY_PASSWORD:discPassword}@${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'


